# Workflow to deploy zot dns zones on a push to main.

name: dnscontrol-check

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
  # branches are defined so the check is done on any branch other than main
  # No change should be committed to main, so check should be done outside
  # of main.  The PR to main will run preview, which will also blow up with
  # any syntax error.
    branches:
      - '**'
      - '!main'
   
env:
  HEXONET_API_LOGIN: ${{ secrets.HEXONET_API_LOGIN }}
  HEXONET_API_SECRET: ${{ secrets.HEXONET_API_SECRET }}
  
# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest

  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: DNSControl push
      uses: koenrh/dnscontrol-action@v3.12.0  
      with:
        args: check

