name: dnscontrol_preview

# pull_request runs the workflow on the pr's repo.  pull_request_target uses the pr target's workflow
# Since the later is safer, pull_request_target allows the use of the target's secrets, while 
# pull_request does not.
on: pull_request

env:
  HEXONET_API_LOGIN: ${{ secrets.HEXONET_API_LOGIN }}
  HEXONET_API_SECRET: ${{ secrets.HEXONET_API_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: merge commit
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'

      - name: DNSControl preview
        uses: koenrh/dnscontrol-action@v3.12.0
        id: dnscontrol_preview
        with:
          args: preview

      - name: Preview pull request comment
        uses: unsplash/comment-on-pr@v1.2.0
        with:
          msg: |
            ```
            ${{ steps.dnscontrol_preview.outputs.preview_comment }}
            ```
          check_for_duplicate_msg: true
